# Generated by Django 3.1.4 on 2020-12-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flyingpet',
            old_name='flyingPet_id',
            new_name='flyingpet_id',
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='gameType_id',
            new_name='gametype_id',
        ),
    ]
